#
# General
# -------------------------------------- #
# -------------------------------------- #
name := log
main := no

#
# Directories
# -------------------------------------- #
# -------------------------------------- #
subdirs := 
CURR_DIR := $(PWD)
include_dirs := -I. \
		   -I$(ROOT_PATH) \
		   -I/usr/local/include/
library_dirs :=
libraries :=

#
# Compiler
# -------------------------------------- #
# -------------------------------------- #
compiler := gcc 
