#
# General
# -------------------------------------- #
# -------------------------------------- #
name := trie-dict
main := yes

#
# Directories
# -------------------------------------- #
# -------------------------------------- #
subdirs :=
submodules :=  ../../log \
	           ../hash
CURR_DIR := $(PWD)
include_dirs := -I. \
		   -I$(ROOT_PATH) \
		   -I/usr/local/include/ \
		   -I../../log/
library_dirs := -L$(shell pwd)/../hash \
				-L$(shell pwd)/../../log
libraries := -lhash -llog

#
# Compiler
# -------------------------------------- #
# -------------------------------------- #
compiler := gcc

LDFLAGS += -Wl,-rpath=$(shell pwd)/../hash -Wl,-rpath=$(shell pwd)/../../log
