#
# General
# -------------------------------------- #
# -------------------------------------- #
name := hash

#
# Directories
# -------------------------------------- #
# -------------------------------------- #
subdirs := 
CURR_DIR := $(PWD)
include_dirs := -I. \
		   -I$(ROOT_PATH) \
		   -I/usr/local/include/ \
		   -I../../log/
library_dirs := -L$(shell pwd)/../hash \
				-L$(shell pwd)/../../log
libraries := -llog

#
# Compiler
# -------------------------------------- #
# -------------------------------------- #
compiler := gcc

LDFLAGS += -Wl,-rpath=$(shell pwd)/../../log
